query TeamsPoints {
  teams {
    id,
    name,
    achievements {
      id,
      challenge {
        id,
        name,
        points
      }
    },
    adjustments {
      id,
      points,
      description
    }
  }
}
